on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Test
        run: go test ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Build
        run: |
          docker build -t devbytom/gcp-idle-resources-metrics:${{ github.sha }} .
  
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
      
      - name: Setup DockerHub
        uses: Mitigram/gh-action-docker-login@main
        with:
          username: devbytom
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish
        run: |
          docker push devbytom/gcp-idle-resources-metrics:${{ github.sha }}
