name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Build and Publish
        uses: opspresso/action-docker@v0.3.9
        with:
          args: --docker
        env:
          USERNAME: devbytom
          PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "devbytom/gcp-idle-resources-metrics"
          TAG_NAME: ${{ github.ref }}
          LATEST: "true"
